---

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: debug-statements
    - id: name-tests-test
    - id: trailing-whitespace

- repo: git://github.com/pre-commit/mirrors-pylint
  sha: v1.7.1
  hooks:
    - id: pylint
      args: [src/tank_utility]

- repo: git://github.com/FalconSocial/pre-commit-python-sorter
  sha: 1.0.4
  hooks:
    - id: python-import-sorter

- repo: git://github.com/pre-commit/mirrors-yapf
  sha: v0.16.1
  hooks:
    - id: yapf
      args: [--in-place --parallel --recursive src]
